/*
 * calc_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package CalcClient

import(
	"calc_lib/configuration_pkg"
	"calc_lib/simplecalculator_pkg"
)


/*
 * Interface for the CALC_IMPL
 */
type CALC interface {
     SimpleCalculator()       simplecalculator_pkg.SIMPLECALCULATOR
     Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the CALC interaface returning CALC_IMPL
 */
func NewCALC() CALC {
    calcClient := new(CALC_IMPL)
    calcClient.config = configuration_pkg.NewCONFIGURATION()
    return calcClient
}
