/*
 * calc_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package CalcClient

import(
	"calc_lib/configuration_pkg"
	"calc_lib/simplecalculator_pkg"
)
/*
 * Client structure as interface implementation
 */
type CALC_IMPL struct {
     simplecalculator simplecalculator_pkg.SIMPLECALCULATOR
     config  configuration_pkg.CONFIGURATION
}

/**
     * Access to Configuration
     * @return Returns the Configuration instance
*/
func (me *CALC_IMPL) Configuration() configuration_pkg.CONFIGURATION {
    return me.config
}
/**
     * Access to SimpleCalculator controller
     * @return Returns the SimpleCalculator() instance
*/
func (me * CALC_IMPL) SimpleCalculator() simplecalculator_pkg.SIMPLECALCULATOR {
    if(me.simplecalculator) == nil {
        me.simplecalculator = simplecalculator_pkg.NewSIMPLECALCULATOR(me.config)
    }
    return me.simplecalculator
}
